var name = "Argho Basak";
var age = 22;
var isStudent = true;
var height = 5.9;
console.log(name, age, isStudent, height);
console.log(typeof name, typeof age, typeof isStudent, typeof height);
var weight = '20';
weight = parseInt(weight);
var price = parseFloat("22.5");
console.log(weight, typeof weight);
var totalPrice = 0.1 + 0.2;
console.log(totalPrice, typeof totalPrice);
console.log(totalPrice.toFixed(2), typeof totalPrice.toFixed(2));